server:
  port: 9091

spring:
  application:
    name: order-service
  rabbitmq:
    host: docker-server
    username: admin
    password: admin
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"

env: dev