server:
  port: 8761

eureka:
  instance:
    hostname: eureka8761
    lease-expiration-duration-in-seconds: 6 # 无心跳认为宕机阈值
    lease-renewal-interval-in-seconds: 3 # 心跳间隔
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8762:8762/eureka/,http://eureka8763:8763/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护
    response-cache-update-interval-ms: 1000 # ReadOnly缓存刷新时间
    eviction-interval-timer-in-ms: 3000 # 心跳检查间隔