server:
  port: 8762

eureka:
  instance:
    hostname: eureka8762
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8761:8761/eureka/,http://eureka8763:8763/eureka/
  server:
    enableSelfPreservation: false